In [51]:
import pandas as pd
import numpy as np

In [52]:
df=pd.read_csv("AirQualityodisha.csv")

In [53]:
df.head()

,Stn Code,Sampling Date,State,City,Location of Monitoring Station,Agency,Type of Location,SO2,NO2,RSPM/PM10,PM 2.5
0,68,02-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,11,24,143,102.0
1,68,06-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,10,23,133,96.0
2,68,09-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,8,25,125,116.0
3,68,13-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,10,25,137,107.0
4,68,16-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,9,26,186,118.0

In [54]:
from sklearn.preprocessing import OneHotEncoder

In [55]:
#df['State'].replace({"Oddisha":1})

In [56]:
df['City'].value_counts()

Bhubaneswar      358
Kalinga Nagar    306
Rourkela         296
Cuttack          277
Angul            210
Rayagada         208
Balasore         200
Talcher          104
Paradeep          96
Berhampur         87
Konark            78
Keonjhar          76
Puri              58
Sambalpur         38
Name: City, dtype: int64

In [57]:
ohe=OneHotEncoder(drop='first')

In [58]:
State=ohe.fit_transform(df[['State']]).toarray()

In [59]:
state_encoded=pd.DataFrame(State)

In [60]:
df=df.drop(columns=['State'])

In [64]:
new_df=np.hstack((df.values,state_encoded))

In [65]:
new_df

array([[68, '02-01-15', 'Talcher', ..., 24, 143, 102.0],
       [68, '06-01-15', 'Talcher', ..., 23, 133, 96.0],
       [68, '09-01-15', 'Talcher', ..., 25, 125, 116.0],
       ...,
       [819, '22-12-15', 'Kalinga Nagar', ..., 10, 90, 38.0],
       [819, '26-12-15', 'Kalinga Nagar', ..., 10, 97, 39.0],
       [819, '29-12-15', 'Kalinga Nagar', ..., 10, 98, 39.0]],
      dtype=object)

In [62]:
df=pd.DataFrame(new_df)

In [66]:
df

,0,1,2,3,4,5,6,7,8,9
0,68,02-01-15,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,11,24,143,102.0
1,68,06-01-15,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,10,23,133,96.0
2,68,09-01-15,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,8,25,125,116.0
3,68,13-01-15,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,10,25,137,107.0
4,68,16-01-15,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,9,26,186,118.0
...,...,...,...,...,...,...,...,...,...,...
2387,819,15-12-15,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,92,35.0
2388,819,17-12-15,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,99,40.0
2389,819,22-12-15,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,90,38.0
2390,819,26-12-15,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,97,39.0
2391,819,29-12-15,Kalinga Nagar,Roof of RO OFFICE BUILDING,Odisha State Pollution Control Board,Industrial Area,2,10,98,39.0